steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-south1-docker.pkg.dev/repaso-microservices/image-registery/auth-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/x86_64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/repaso-microservices/image-registery/auth-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
